apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cicd-service-user-role-global
subjects:
- kind: Group
  name: admin-service-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin-cicd-service-user-role
  apiGroup: rbac.authorization.k8s.io